# ml-app-eks.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-app
  template:
    metadata:
      labels:
        app: ml-app
    spec:
      containers:
      - name: ml-app-container
        # Replace ACCOUNT-ID and REGION
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ml-app-svc
  annotations:
    # Public Network Load Balancer, managed by the AWS Load Balancer Controller
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip   # (instance | ip)
spec:
  type: LoadBalancer
  # On clusters created with new *EKS Auto Mode* you can leave this line out,
  # but adding it is harmless and future-proof:
  loadBalancerClass: eks.amazonaws.com/nlb
  selector:
    app: ml-app
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
