apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-app
  template:
    metadata:
      labels:
        app: ml-app
    spec:
      containers:
      - name: ml-app-container
        image: IMAGE_PLACEHOLDER   # <-- replaced by Jenkins sed
        ports:
        - containerPort: 5000
        # (recommended) add basic health checks + small resources
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ml-app-svc
  annotations:
    # Public Network Load Balancer
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip  # (instance|ip)
spec:
  type: LoadBalancer
  # On new EKS Auto Mode clusters this can be omitted, but harmless to keep:
  loadBalancerClass: eks.amazonaws.com/nlb
  selector:
    app: ml-app
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
